In [ ]:
import tensorflow as tf

In [ ]:
# Initializing tensors

x = tf.constant([[1, 2]])
print(x.shape)
# TensorShape([1, 2]) # one entity of two items
print(x.dtype)
# <dtype: 'int32'>

y = tf.constant([[1], [2]])
print(y.shape)
# TensorShape([2, 1]) # two entities of one item each
print(y.dtype)
# <dtype: 'int32'>

M0 = tf.zeros((3, 4))
print(M0)
# <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
# array([[0., 0., 0., 0.],
#        [0., 0., 0., 0.],
#        [0., 0., 0., 0.]], dtype=float32)>

M1 = tf.ones((3, 4))
print(M1)
# <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
# array([[1., 1., 1., 1.],
#        [1., 1., 1., 1.],
#        [1., 1., 1., 1.]], dtype=float32)>

Mr = tf.random.uniform((3, 4))
print(Mr)
# <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
# array([[0.8603865 , 0.67271686, 0.6483016 , 0.20570433],
#        [0.11326289, 0.18726146, 0.5950843 , 0.1431241 ],
#        [0.6015377 , 0.71520114, 0.60601425, 0.21764886]], dtype=float32)>

Mrn = tf.random.normal((3, 4))
print(Mrn)
# <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
# array([[-0.02117053,  1.1006633 , -0.6750533 , -0.6749519 ],
#        [-0.09153239, -1.6069647 ,  0.17528066, -0.67438143],
#        [ 0.05407016, -0.63913435, -0.8488226 ,  0.17544864]], dtype=float32)>

Mrlh = tf.random.uniform((3, 4), minval=0, maxval=10, dtype=tf.int32)
print(Mrlh)
# <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
# array([[0, 9, 5, 2],
#        [4, 3, 5, 6],
#        [4, 8, 6, 1]], dtype=int32)>


In [ ]:
# Operations on tensors

# Multiply to all
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=tf.float32)
print(x * 10)
# <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
# array([[10., 20., 30., 40.],
#        [50., 60., 70., 80.]], dtype=float32)>

# Add to all
print(tf.add(x, 10))
# <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
# array([[11., 12., 13., 14.],
#        [15., 16., 17., 18.]], dtype=float32)>

# Reshape (contiguous tensor) to 1x8
print(tf.reshape(x, (1, 8)))
# <tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6., 7., 8.]], dtype=float32)>

# Reshape (contiguous tensor) to 8x1
print(tf.reshape(x, (8, 1)))
# <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
# array([[1.],
#        [2.],
#        [3.],
#        [4.],
#        [5.],
#        [6.],
#        [7.],
#        [8.]], dtype=float32)>

# Reshape (possibly non-contiguous tensor) to 1x8
print(tf.reshape(x, (1, 8)))
# <tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6., 7., 8.]], dtype=float32)>

# Reshape (possibly non-contiguous tensor) to 8x1
print(tf.reshape(x, (8, 1)))
# <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
# array([[1.],
#        [2.],
#        [3.],
#        [4.],
#        [5.],
#        [6.],
#        [7.],
#        [8.]], dtype=float32)>

# Squeezing
y = tf.random.normal((1, 4, 5))
print(tf.squeeze(y, 0).shape)
# TensorShape([4, 5])

y = tf.random.normal((4, 1, 5))
print(tf.squeeze(y, 1).shape)
# TensorShape([4, 5])

y = tf.random.normal((4, 5, 1))
print(tf.squeeze(y, 2).shape)
# TensorShape([4, 5])

# Unsqueezing
y = tf.random.normal((4, 5))
print(tf.expand_dims(y, 0).shape)
# TensorShape([1, 4, 5])
print(tf.expand_dims(y, 1).shape)
# TensorShape([4, 1, 5])
print(tf.expand_dims(y, 2).shape)
# TensorShape([4, 5, 1])

# Matrix multiplication
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=tf.float32)
y = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=tf.float32)
print(tf.matmul(x, y))
# <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
# array([[ 50.,  60.],
#        [114., 140.]], dtype=float32)>

# Concatenate
x = tf.random.normal((10, 10, 10))
print(tf.concat([x, x], axis=0).shape)
# TensorShape([20, 10, 10])
print(tf.concat([x, x], axis=1).shape)
# TensorShape([10, 20, 10])
print(tf.concat([x, x], axis=2).shape)
# TensorShape([10, 10, 20])

# Arange
x = tf.range(25)
print(x)
# <tf.Tensor: shape=(25,), dtype=int32, numpy=
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
#        18, 19, 20, 21, 22, 23, 24])>