In [ ]:
import tensorflow as tf

In [ ]:
# Initializing tensors

x = tf.constant([[1, 2]])
print(x.shape)
# (1, 2) # one entity of two items
print(x.dtype)
# <dtype: 'int32'>

y = tf.constant([[1], [2]])
print(y.shape)
# (2, 1) # two entities of one item each
print(y.dtype)
# <dtype: 'int32'>

M0 = tf.zeros((3, 4))
print(M0)
# tf.Tensor(
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)

M1 = tf.ones((3, 4))
print(M1)
# tf.Tensor(
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)

Mr = tf.random.uniform((3, 4))
print(Mr)
# tf.Tensor(
# [[0.0133332  0.57062876 0.2544589  0.15649104]
#  [0.6489532  0.19631803 0.670375   0.01787996]
#  [0.7631719  0.92131424 0.56712353 0.44069576]], shape=(3, 4), dtype=float32)

Mrn = tf.random.normal((3, 4))
print(Mrn)
# tf.Tensor(
# [[ 0.13419475 -0.70725274 -0.01478264  0.25297415]
#  [-0.72948587  0.30781922 -0.48637235  0.04656595]
#  [ 1.33248     0.17864135  0.626725   -1.037374  ]], shape=(3, 4), dtype=float32)

Mrlh = tf.random.uniform((3, 4), minval=0, maxval=10, dtype=tf.int32)
print(Mrlh)
# tf.Tensor(
# [[1 5 6 8]
#  [2 7 0 9]
#  [1 9 0 6]], shape=(3, 4), dtype=int32)


In [ ]:
# Operations on tensors

# Multiply to all
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=tf.float32)
print(x * 10)
# tf.Tensor(
# [[10. 20. 30. 40.]
#  [50. 60. 70. 80.]], shape=(2, 4), dtype=float32)

# Add to all
print(tf.add(x, 10))
# tf.Tensor(
# [[11. 12. 13. 14.]
#  [15. 16. 17. 18.]], shape=(2, 4), dtype=float32)

# Reshape (contiguous tensor) to 1x8
print(tf.reshape(x, (1, 8)))
# tf.Tensor([[1. 2. 3. 4. 5. 6. 7. 8.]], shape=(1, 8), dtype=float32)

# Reshape (contiguous tensor) to 8x1
print(tf.reshape(x, (8, 1)))
# tf.Tensor(
# [[1.]
#  [2.]
#  [3.]
#  [4.]
#  [5.]
#  [6.]
#  [7.]
#  [8.]], shape=(8, 1), dtype=float32)

# Squeezing
y = tf.random.normal((1, 4, 5))
print(tf.squeeze(y, 0).shape)
# (4, 5)

y = tf.random.normal((4, 1, 5))
print(tf.squeeze(y, 1).shape)
# (4, 5)

y = tf.random.normal((4, 5, 1))
print(tf.squeeze(y, 2).shape)
# (4, 5)

# Unsqueezing
y = tf.random.normal((4, 5))
print(tf.expand_dims(y, 0).shape)
# (1, 4, 5)
print(tf.expand_dims(y, 1).shape)
# (4, 1, 5)
print(tf.expand_dims(y, 2).shape)
# (4, 5, 1)

# Matrix multiplication
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=tf.float32)
y = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=tf.float32)
print(tf.matmul(x, y))
# tf.Tensor(
# [[ 50.  60.]
#  [114. 140.]], shape=(2, 2), dtype=float32)

# Concatenate
x = tf.random.normal((10, 10, 10))
print(tf.concat([x, x], axis=0).shape)
# (20, 10, 10)
print(tf.concat([x, x], axis=1).shape)
# (10, 20, 10)
print(tf.concat([x, x], axis=2).shape)
# (10, 10, 20)

# Arange
x = tf.range(25)
print(x)
# tf.Tensor(
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
#  24], shape=(25,), dtype=int32)