In [ ]:
import torch

In [ ]:
# Initializing tensors

x = torch.tensor([[1,2]])
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(x.dtype)
# torch.int64

y = torch.tensor([[1],[2]])
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(y.dtype)
# torch.int64

M0 = torch.zeros((3, 4))
print(M0)
# tensor([[0., 0., 0., 0.],
#         [0., 0., 0., 0.],
#         [0., 0., 0., 0.]])    # equivalent to a zeros matrix of dimensions 3x4

M1 = torch.ones((3, 4))
print(M1)
# tensor([[1., 1., 1., 1.],
#         [1., 1., 1., 1.],
#         [1., 1., 1., 1.]])    # equivalent to a ones matrix of dimensions 3x4

Mr = torch.rand(3, 4)
print(Mr)
# tensor([[0.1066, 0.8497, 0.0035, 0.5398],
#         [0.1960, 0.0018, 0.3579, 0.4024],
#         [0.8017, 0.4062, 0.4873, 0.2197]])    # equivalent to a random {uniform distribution in the interval [0,1)}
#                                                 matrix of dimensions 3x4

Mrn = torch.randn(3, 4)
print(Mrn)
# tensor([[0.1066, 0.8497, 0.0035, 0.5398],
#         [0.1960, 0.0018, 0.3579, 0.4024],
#         [0.8017, 0.4062, 0.4873, 0.2197]])    # equivalent to a random {standard normal distribution (mean value is 0, 
#                                                 variance is 1, that is,  Gaussian white noise)} matrix of dimensions 3x4

Mrlh = torch.randint(low=0, high=10, size=(3,4))
print(Mrlh)
# tensor([[1, 2, 3, 4],
#         [0, 2, 9, 6],
#         [5, 0, 1, 5]])    # equivalent to a random (range low to high) matrix of dimensions 3x4


In [ ]:
# Operations on tensors

# Multiply to all
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(x * 10)
# tensor([[10, 20, 30, 40],
#         [50, 60, 70, 80]])

# Add to all
print(x.add(10))
# tensor([[11, 12, 13, 14],
#         [15, 16, 17, 18]])

# Reshape (continguous tensor) to 1x8
print(x.view(1, 8))
# tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

# Reshape (continguous tensor) to 8x1
print(x.view(8, 1))
# tensor([[1],
#         [2],
#         [3],
#         [4],
#         [5],
#         [6],
#         [7],
#         [8]])

# Reshape (possibly non-continguous tensor) to 1x8
print(x.reshape(1, 8))
# tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

# Reshape (possibly non-continguous tensor) to 8x1
print(x.reshape(8, 1))
# tensor([[1],
#         [2],
#         [3],
#         [4],
#         [5],
#         [6],
#         [7],
#         [8]])

# Squeezing
y = torch.randn(1,4,5)
print(torch.squeeze(y, 0).shape)
# torch.Size([4, 5])

y = torch.randn(4,1,5)
print(torch.squeeze(y, 1).shape)
# torch.Size([4, 5])

y = torch.randn(4,5,1)
print(torch.squeeze(y, 2).shape)
# torch.Size([4, 5])

# Unsqueezing
y = torch.randn(4,5)
print(torch.unsqueeze(y, 0).shape)
# torch.Size([1, 4, 5])
print(torch.unsqueeze(y, 1).shape)
# torch.Size([4, 1, 5])
print(torch.unsqueeze(y, 2).shape)
# torch.Size([4, 5, 1])

# Matrix multiplication
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
y = torch.tensor([[1,2], [3,4], [5,6], [7,8]])
print(torch.matmul(x, y))   # same output as x@y
# tensor([[ 50,  60],
#         [114, 140]])

# Concatenate
x = torch.randn(10,10,10)
print(torch.cat([x,x], axis=0).shape)
# torch.Size([20, 10, 10])
print(torch.cat([x,x], axis=1).shape)
# torch.Size([10, 20, 10])
print(torch.cat([x,x], axis=2).shape)
# torch.Size([10, 10, 20])

# Arange
x = torch.arange(25)
print(x)
# tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
#         18, 19, 20, 21, 22, 23, 24])